### ISSUE TITLE
Olá, Boa tarde.

### ISSUE THREAD

**Issue by binhoz** [deniscsz/Magento-Jamef-Carrier#2]
Olá, boa tarde..
eu instalei o modulo em meu magento e agora quando entro no carrinho ele me volta esse erro:

Invalid method Spalenza_Jamef_Model_Carrier_Jamef::__(Array
(
    [0] => Out of Area
)
)
#0 /Volumes/Storage/Documentos/projectX/project/app/code/community/Spalenza/Jamef/Model/Carrier/Jamef.php(242): Varien_Object->**call('**', Array)
#1 /Volumes/Storage/Documentos/projectX/project/app/code/community/Spalenza/Jamef/Model/Carrier/Jamef.php(242): Spalenza_Jamef_Model_Carrier_Jamef->__('Out of Area')
#2 /Volumes/Storage/Documentos/projectX/project/app/code/community/Spalenza/Jamef/Model/Carrier/Jamef.php(38): Spalenza_Jamef_Model_Carrier_Jamef->_inicialCheck(Object(Mage_Shipping_Model_Rate_Request))
#3 /Volumes/Storage/Documentos/projectX/project/app/code/core/Mage/Shipping/Model/Shipping.php(209): Spalenza_Jamef_Model_Carrier_Jamef->collectRates(Object(Mage_Shipping_Model_Rate_Request))
#4 /Volumes/Storage/Documentos/projectX/project/app/code/core/Mage/Shipping/Model/Shipping.php(129): Mage_Shipping_Model_Shipping->collectCarrierRates('spalenza_jamef', Object(Mage_Shipping_Model_Rate_Request))
#5 /Volumes/Storage/Documentos/projectX/project/app/code/core/Mage/Sales/Model/Quote/Address.php(944): Mage_Shipping_Model_Shipping->collectRates(Object(Mage_Shipping_Model_Rate_Request))
#6 /Volumes/Storage/Documentos/projectX/project/app/code/core/Mage/Sales/Model/Quote/Address.php(875): Mage_Sales_Model_Quote_Address->requestShippingRates()
#7 /Volumes/Storage/Documentos/projectX/project/app/code/core/Mage/Sales/Model/Quote/Address/Total/Shipping.php(155): Mage_Sales_Model_Quote_Address->collectShippingRates()
#8 /Volumes/Storage/Documentos/projectX/project/app/code/core/Mage/Sales/Model/Quote/Address.php(1013): Mage_Sales_Model_Quote_Address_Total_Shipping->collect(Object(Mage_Sales_Model_Quote_Address))
#9 /Volumes/Storage/Documentos/projectX/project/app/code/core/Mage/Sales/Model/Quote.php(1331): Mage_Sales_Model_Quote_Address->collectTotals()
#10 /Volumes/Storage/Documentos/projectX/project/app/code/core/Mage/Checkout/Model/Cart.php(458): Mage_Sales_Model_Quote->collectTotals()
#11 /Volumes/Storage/Documentos/projectX/project/app/code/core/Mage/Checkout/controllers/CartController.php(144): Mage_Checkout_Model_Cart->save()
#12 /Volumes/Storage/Documentos/projectX/project/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_CartController->indexAction()
#13 /Volumes/Storage/Documentos/projectX/project/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#14 /Volumes/Storage/Documentos/projectX/project/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#15 /Volumes/Storage/Documentos/projectX/project/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#16 /Volumes/Storage/Documentos/projectX/project/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#17 /Volumes/Storage/Documentos/projectX/project/index.php(83): Mage::run('', 'store')
#18 {main}

gostaria de uma luz do que poderia estar acontecendo, configurei certinho no adm.. 
e também o dropdown dos estados só funciona quando o pais é o EUA, quando coloca brasil ele não funciona tb.. enfim, se possível aguardo uma resposta!

Gratidão!

**Comment by binhoz** [comment]
Man, já consegui! faltou configurar a questão da localização do envio, tava travando aqui:
 if ($origCountry != 'BR' || $destCountry != 'BR') {
                $this->getHelper()->writeLog($this->__('Out of Area'));
                return false;
            }
AUHAUH

valew :) \o>

**Comment by deniscsz** [comment]
Oi Fábio. Que bom que deu certo rs.
O "Out of Area" seria para apontar que está fora da área de cobertura da
Jamef.

Além disso tem um bug nesse módulo que eu arrumei mas não fiz commit. Fazia
com que o preço viesse incorreto.
Irei atualizar esse final de semana para você puxar.

Denis Colli Spalenza

2016-02-24 17:23 GMT-03:00 Fábio C. Nogueira notifications@github.com:

**Comment by binhoz** [comment]
Opa! ;) bom dia Denis! 
deu certo sim! depois acabei de percebendo a parte de cubagem também, criei os atributos e aconteceu algo estranho! a primeira vez que entro no carrinho ele pega o valor do array de cubagem, mas se eu atualizo o carrinho o valor da cubagem zera, mas somente o da cubagem, o peso e os outros atributos continuam normais.. achei meio estranho isso.. to tentando entender o que ta acontecendo!
De qualquer forma muito obrigado pelo feedback da resposta! 
fico no aguardo da atualização! \o

Gratidão! 
Fábio Cavalcante Nogueira
