### ISSUE TITLE
Boa tarde

### ISSUE THREAD

**Issue by binhoz** [deniscsz/Magento-Jamef-Carrier#3]
Olá boa tarde, eu aqui de novo! :)

percebi que quando você finaliza o pedido, mesmo pedindo pra atualizar o valor no carrinho, ele mantem um valor antigo que teria feito em outra compra, exemplo, fiz uma compra deu 92,00 de frente, beleza! fiz outra compra deu 87,00 dae no carrinho eu mandei atualizar o valor, atualizou certo, agora no pagina de finalização do pedido, ele aparece o valor do frente de 92,00, o valor antigo..

seria em relação aos valores que cê disse que ia subir agora final de semana?

Abraço!
obrigado pela atenção!

**Comment by deniscsz** [comment]
@binhoz Desculpa a demora, acabou ficando esquecida a issue.
Eu acredito que sim, a 10 meses eu fiz um commit que corrigia isso. Dada a lentidão do webservice da Jamef eu meio que desanimei desse WebService porque a cotação estava muito lenta e atualmente uso tabela mesmo.
