### ISSUE TITLE
Dados para a cotação

### ISSUE THREAD

**Issue by ebanolopes** [deniscsz/Magento-Jamef-Carrier#4]
Fera, peguei o módulo por indicação de um cliente, que não entende de tecnologia e achou o módulo na Internet. Rapaz, no arquivo app/code/community/Spalenza/Jamef/Model/Carrier/Jamef.php você pega todos os dados do carrinho, isto está errado. Os carriers no Magento recebem um objeto do request que gerou o pedido de cotação e devem se basear nele para fazer a cotação. Isto dá problema, por exemplo, pra calcular frete na página do produto; se eu coloco 10 itens no carrinho, ao invés de calcular o frete pro produto que estou na página, vai calcular pros 10 itens do carrinho e ignorar o meu produto, que é o que os módulos de cálculo de frete na página do produto passam pro carrier.

Do resto o módulo parece estar muito bom, ainda não coloquei em produção. Mas parabéns pela iniciativa, sei o trabalhão que isto dá.

**Comment by deniscsz** [comment]
Olá @ebanolopes, sim, você está completamente correto. 

Há outros erros na versão que está disponível nesse repositório. Eu não publiquei a versão final desse módulo que conta com estimativa de prazo e com outras correções e implementações justamente porque não houve colaboração, então parei de publicar os commits para esse repositório remoto. 

Além desse problema que você citou, fica uma dica a respeito dessa versão já que vai utilizá-lo. Também há um problema a respeito do cálculo do peso (veja a função getInformations, vai encontrar rapidamente). Se quiser contribuir, fique a vontade, aceitarei o PR. 

Obrigado e grande abraço.

**Comment by deniscsz** [comment]
@ebanolopes Fiquei com peso na consciência (hahaha) e acabei publicando dois fixes aqui (https://github.com/deniscsz/Magento-Jamef-Carrier/commit/16ccc3407d667ca6466bba4a2c3b9c97983cc9ca), visto que realmente tem gente usando o módulo. Abraço.

**Comment by ebanolopes** [comment]
Opa! Mas que beleza, rapaz! Valeu mesmo :) Eu ia até corrigir e te mandar, mas já arrumou ai, show!
